version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - '${REDIS_PORT}'
    volumes:
      - ./redis:/data
